# Site settings
title: GenderMeme
email: viswa@cs.stanford.edu
description: "GenderMeme"
baseurl: ""
url: "http://viswajithiii.github.io/gendermeme/"
twitter_username: viswajithiii
github_username: viswajithiii

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

